// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL7yxbYpqTGYgWU4sdPDb4Sp9Rb6FtDRg',
    appId: '1:505910735096:web:b64b7735e2b65be8354b0d',
    messagingSenderId: '505910735096',
    projectId: 'task-app1-ed2cc',
    authDomain: 'task-app1-ed2cc.firebaseapp.com',
    storageBucket: 'task-app1-ed2cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqx8R7ZccaXfsZtJCNRGfSW43XEvdQueU',
    appId: '1:505910735096:android:f626b1b1a7cb5028354b0d',
    messagingSenderId: '505910735096',
    projectId: 'task-app1-ed2cc',
    storageBucket: 'task-app1-ed2cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEOAExJ1r3aWJ-zDwt-Gur_3IKw9hqSZQ',
    appId: '1:505910735096:ios:3e26639e7acf1dff354b0d',
    messagingSenderId: '505910735096',
    projectId: 'task-app1-ed2cc',
    storageBucket: 'task-app1-ed2cc.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEOAExJ1r3aWJ-zDwt-Gur_3IKw9hqSZQ',
    appId: '1:505910735096:ios:3e26639e7acf1dff354b0d',
    messagingSenderId: '505910735096',
    projectId: 'task-app1-ed2cc',
    storageBucket: 'task-app1-ed2cc.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL7yxbYpqTGYgWU4sdPDb4Sp9Rb6FtDRg',
    appId: '1:505910735096:web:186e61a82281ea33354b0d',
    messagingSenderId: '505910735096',
    projectId: 'task-app1-ed2cc',
    authDomain: 'task-app1-ed2cc.firebaseapp.com',
    storageBucket: 'task-app1-ed2cc.firebasestorage.app',
  );
}
